import type { Metadata } from "next";
import { Suspense } from "react";

import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="min-h-screen bg-gray-50">
            <div className="flex gap-7">
                <div className="flex-shrink-0">
                    <Suspense fallback={<div>Loading...</div>}>
                        <Sidebar />
                    </Suspense>
                </div>
                <div className="flex-1 min-w-0">
                    {children}
                </div>
            </div>
        </div>
    );
}